function Main() {
  return (
    <div className="bg-black text-white p-2 overflow-y-auto border">
      <div className="border">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus, in consectetur ex quas vero iusto totam mollitia, a rem accusamus, incidunt temporibus quam sint aperiam deleniti eos delectus tenetur fugit provident iure non! Explicabo vel commodi nulla illo aliquid facere, excepturi odio modi cumque officia fugit animi dolorem voluptatum quis tempore non quibusdam soluta consectetur delectus velit suscipit voluptatibus laudantium fuga placeat. Necessitatibus, placeat recusandae molestias minima voluptate amet exercitationem tempore quos corrupti asperiores aut dolores officia dicta dolore cupiditate quisquam ratione modi laudantium molestiae sit facilis reiciendis? Ea est ad minima eos accusamus quas laborum sunt laboriosam, ipsa ut consequatur cumque tenetur sint voluptate repudiandae fugit commodi laudantium tempora maiores eum. Quasi cum omnis voluptates illum debitis expedita quaerat explicabo soluta corporis mollitia dolorum recusandae minima, reprehenderit eligendi repellendus unde voluptate blanditiis nesciunt. Tempora maiores quasi tempore qui temporibus placeat neque nulla facilis illo suscipit, possimus reprehenderit non, voluptates pariatur minus assumenda quia et, molestias ex doloribus perspiciatis velit iste labore quisquam! Deserunt unde iste assumenda quam molestiae cumque culpa delectus maxime velit veniam ullam aspernatur, magnam tempore numquam ex modi illo temporibus itaque reiciendis deleniti, exercitationem suscipit. Quae commodi illo distinctio saepe nostrum ullam ipsam excepturi eaque ex!
      </div>
      <div className="border">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus, in consectetur ex quas vero iusto totam mollitia, a rem accusamus, incidunt temporibus quam sint aperiam deleniti eos delectus tenetur fugit provident iure non! Explicabo vel commodi nulla illo aliquid facere, excepturi odio modi cumque officia fugit animi dolorem voluptatum quis tempore non quibusdam soluta consectetur delectus velit suscipit voluptatibus laudantium fuga placeat. Necessitatibus, placeat recusandae molestias minima voluptate amet exercitationem tempore quos corrupti asperiores aut dolores officia dicta dolore cupiditate quisquam ratione modi laudantium molestiae sit facilis reiciendis? Ea est ad minima eos accusamus quas laborum sunt laboriosam, ipsa ut consequatur cumque tenetur sint voluptate repudiandae fugit commodi laudantium tempora maiores eum. Quasi cum omnis voluptates illum debitis expedita quaerat explicabo soluta corporis mollitia dolorum recusandae minima, reprehenderit eligendi repellendus unde voluptate blanditiis nesciunt. Tempora maiores quasi tempore qui temporibus placeat neque nulla facilis illo suscipit, possimus reprehenderit non, voluptates pariatur minus assumenda quia et, molestias ex doloribus perspiciatis velit iste labore quisquam! Deserunt unde iste assumenda quam molestiae cumque culpa delectus maxime velit veniam ullam aspernatur, magnam tempore numquam ex modi illo temporibus itaque reiciendis deleniti, exercitationem suscipit. Quae commodi illo distinctio saepe nostrum ullam ipsam excepturi eaque ex!
      </div>
    </div>
  )
}
export default Main